namespace :db do
  desc "Bootstraps the database with demo data"
  task :bootstrap => %w(db:setup) do
    User.create(:name => "Silvio Santos")
    Post.create! :title => "A incogniscibilidade pós-moderna do Ser.", :body => "p. Caros amigos, a infinita diversidade da realidade única nos obriga à análise das condições epistemológicas e cognitivas exigidas. Por outro lado, a intencionalidade do sujeito volitivo cumpre um papel essencial na formulação das convicções empiristas. Assim mesmo, a estrutura atual da ideação semântica exige a precisão e a definição do sistema de conhecimento geral. No entanto, não podemos esquecer que o novo modelo estruturalista aqui preconizado tem que apresentar uma homogenidade em relação aos extremos das posturas dos filósofos divergentes com relação às atribuições conceituais.\np.Evidentemente, a indeterminação contínua de distintas formas de fenômeno garante a contribuição de um grupo importante na determinação da corrente inovadora da qual fazemos parte. A prática cotidiana prova que a consolidação das estruturas psico-lógicas assume importantes posições no estabelecimento das direções preferenciais no sentido do progresso filosófico. Nunca é demais lembrar o peso e o significado destes problemas, uma vez que o conceito de diáthesis e os princípios fundamentais de rhytmos e arrythmiston facilita a criação do sistema de formação de quadros que corresponde às necessidades lógico-estruturais. Como Deleuze eloquentemente mostrou, o início da atividade geral de formação de conceitos obstaculiza a apreciação da importância dos limites da ação do Estado.\np.    Acabei de provar que o desafiador cenário globalizado não oferece uma interessante oportunidade para verificação das múltiplas direções do ponto de transcendência do sentido enunciativo. Se estivesse vivo, Foucault diria que o Übermensch de Nietzsche, ou seja, o Super-Homem, acarreta um processo de reformulação e modernização do processo de comunicação como um todo. Pretendo demonstrar que a expansão dos mercados mundiais institui o Complexo de Édipo, ordenando o sujeito com seu desejo e o interdito, em função das ciências discursivas.", :author => User.last
    Post.create! :title => "Vivencia em um mundo sobre o paradigma birelacional", :body => "p.Uma posição análoga, embora um tanto foucaultiana, defende que o desafiador cenário globalizado não oferece uma interessante oportunidade para verificação do prazer e da dor. Se estivesse vivo, Foucault diria que o Übermensch de Nietzsche, ou seja, o Super-Homem, acarreta um processo de reformulação e modernização do processo de comunicação como um todo. Pretendo demonstrar que a consolidação das estruturas psico-lógicas pode nos levar a considerar a reestruturação das ciências discursivas. Com base nesses argumentos, a hegemonia do ambiente político corresponde à intuição das essências fenomenológicas da sensibilia dos não-sentidos.\np.Segundo Heidegger, o fenômeno da Internet ainda não demonstrou convincentemente como vai participar na mudança das múltiplas direções do ponto de transcendência do sentido enunciativo. É lícito um filósofo restringir suas investigações ao mundo fenomênico, mas o aumento do diálogo entre os diferentes setores filosóficos talvez venha a ressaltar a relatividade de universos de Contemplação, espelhados na arte minimalista e no expressionismo abstrato, absconditum. Este pensamento está vinculado à desconstrução da metafísica, pois a limitação dos poderes do narcisismo prepara-nos para enfrentar situações atípicas decorrentes de todos os recursos funcionais envolvidos. A certificação de metodologias que nos auxiliam a lidar com o silogismo hipotético, sob a perspectiva kantiana dos juízos infinitos, maximiza as possibilidades por conta da corrente inovadora da qual fazemos parte.", :author => User.last
    Post.create! :title => "Para o mundo que eu quero descer", :body => "p.O empenho em analisar a univocidade da substância imanente aponta para a melhoria das novas teorias propostas. A prática cotidiana prova que a expansão dos mercados mundiais assume importantes posições no estabelecimento das direções preferenciais no sentido do progresso filosófico. Nunca é demais lembrar o peso e o significado destes problemas, uma vez que a instauração do modo aporético do Uno é condição necessária e suficiente do investimento em reciclagem ideológica.\np. Como Deleuze eloquentemente mostrou, o mundo supra-celeste como modelo eterno institui o Complexo de Édipo, ordenando o sujeito com seu desejo e o interdito, em função dos paradigmas filosóficos. Uma posição análoga, embora um tanto foucaultiana, defende que o desafiador cenário globalizado não oferece uma interessante oportunidade para verificação do prazer e da dor. Se estivesse vivo, Foucault diria que o Übermensch de Nietzsche, ou seja, o Super-Homem, acarreta um processo de reformulação e modernização do processo de comunicação como um todo.", :author => User.last
    Post.all.each do |post|
      post.publish!
    end
  end
end
